[project]
name = "stupeter12138-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nasa-apod>=1.0.3",
    "openai>=1.78.0",
    "rich>=14.0.0",
]
