# hello_toml.toml
# 键值对
int1 = 1
flt1 = 1.0e-2
bool1 = true
key = "value"
str = "Roses are red\nViolets are blue"
array = [[1, 2, 3.0], [4.0, 5, 6]]
# 字面量字符串
winpath  = 'C:\Users\nodejs\templates'
# 表
[table]
key1 = "hello"
key2 = "world"
