name: Sync README

on:
  push:
    paths:
      - 'docs/**'
      - 'scripts/sync_blog_to_readme.py'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 使用与您项目中一致的Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 如果您的脚本有依赖，请在此处安装
          # pip install -r scripts/requirements.txt # 假设依赖在requirements.txt中

      - name: Run script to update README
        run: python scripts/sync_blog_to_readme.py

      - name: Commit and push if README changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull origin main
          git add README.md
          # 检查是否有更改，只有在有更改时才提交
          if ! git diff --staged --quiet; then
            git commit -m "Automated README update"
            git push
          else
            echo "No changes to README.md"
          fi