name: Update

on:
  # manual trigger only
  workflow_dispatch:

jobs:
  version_update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          source_repo_path: Yousa-Mirage/Tufted-Blog-Template
          upstream_branch: main
          pr_labels: version_update